steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west4-docker.pkg.dev/qwiklabs-gcp-03-e0f23998d4ae/my-repository/hello-app:v1.0', '.' ]
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-west4-docker.pkg.dev/qwiklabs-gcp-03-e0f23998d4ae/my-repository/hello-app:v1.0' ]
  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'prod/deployment.yaml', '--namespace=prod' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
options:
  logging: CLOUD_LOGGING_ONLY
