apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-deployment
  template:
    metadata:
      labels:
        app: production-deployment
    spec:
      containers:
      - name: hello-app
        image: europe-west4-docker.pkg.dev/qwiklabs-gcp-03-e0f23998d4ae/my-repository/hello-app:v1.0
        ports:
        - containerPort: 8080
